name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  create-release:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    env:
      TAG: ${{ github.ref_name }}
    steps:
      - uses: actions/checkout@v4
      - name: docker login
        continue-on-error: true
        run: (echo ${{ secrets.GITHUB_TOKEN }} | docker login ${CI_CONTAINER_REGISTRY} -u ${GITHUB_ACTOR} --password-stdin)
      # Needed so the container has permission to create files.
      - name: container user repository file permissions
        run: chmod -R o+rw .
      - name: build
        run: make container run="make build"
      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create "${TAG}" \
            --repo="$GITHUB_REPOSITORY" \
            --title="${GITHUB_REPOSITORY#*/} ${TAG#v}" \
            --generate-notes \
            --verify-tag \
            --notes "sha256: `$(sha256sum bin/sqlc-template.wasm | cut -f 1 -d ' ')`\n\n``` yaml\nversion: '2'\nplugins:- name: sqlc-template\n  wasm:\n    url: https://github.com/${TAG}/sqlc-template.wasm\n    sha256: $(sha256sum bin/sqlc-template.wasm | cut -f 1 -d ' ')\n```" \
            "bin/sqlc-template.wasm"
